services:
  db:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: rust_backend
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/app/Frontend  # Montar el frontend como volumen
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"

volumes:
  postgres_data: